./brk > brk.out
./chdir > chdir.out
./clone > clone.out
./close > close.out
./dup > dup.out
./dup2 > dup2.out
./execve > execve.out
./exit > exit.out
./fork > fork.out
./fstat > fstat.out
./getcwd > getcwd.out
./getdents > getdents.out
./getpid > getpid.out
./getppid > getppid.out
./gettimeofday > gettimeofday.out
./mkdir_ > mkdir_.out
./mmap > mmap.out
./mount > mount.out
./munmap > munmap.out
./open > open.out
./openat > openat.out
./pipe > pipe.out
./read > read.out
./sleep > sleep.out
./test_echo > test_echo.out
./times > times.out
./umount > umount.out
./uname > uname.out
./unlink > unlink.out
./wait > wait.out
./waitpid > waitpid.out
./write > write.out
./yield > yield.out